### ISSUE TITLE
Do I have access?

### ISSUE THREAD

**Issue by CLuiz** [arsenyturin/mentorship-repo#1]

**Comment by CLuiz** [comment]
@arseniyturin  I can create issues but not manage assignees/labels/etc. Can you add me as a collaborator?

**Comment by CLuiz** [comment]
I'll need collaborator/admin access on the project board as well.

**Comment by arsenyturin** [comment]
@CLuiz fixed it. Should work now

**Comment by CLuiz** [comment]
Confirmed fixed, thanks!
