### ISSUE TITLE
Mentorship Goals

### ISSUE THREAD

**Issue by CLuiz** [arsenyturin/mentorship-repo#3]
List top mentorship goals

**Comment by CLuiz** [comment]
* Goal 1
* Goal 2

**Comment by arsenyturin** [comment]
Hi Chris, these are my expectations from the mentorship:

- [ ] Find a Job as a Data Scientist / Analyst / ML Engineer
- [ ] Learn leadership qualities
- [ ] Salary expectations: 100k
- [ ] Preferably in NYC. I would also consider Boston, Austin, and cities close to the east coast
- [ ] Company in fintech, marketing, IT (I think I have a little chance to land something in healthcare)
- [ ] Be a part of the DS team with an opportunity to learn and grow from senior members
- [ ] The possibility to work remote is a plus

**Comment by CLuiz** [comment]
Added to the sidebar. Closing as complete.
