### ISSUE TITLE
Daily ML Card Review Sprint 7/30

### ISSUE THREAD

**Issue by CLuiz** [arsenyturin/mentorship-repo#5]
### Acceptance Criteria
- [x] Monday
- [x] Tuesday
- [ ] Wednesday
- [x] Thursday
- [ ] Friday
- [x] Saturday
- [x] Sunday

Capture concepts covered and any notes in the issue comments. Commit 15 minutes per day for now.

**Comment by CLuiz** [comment]
@arseniyturin use the above as a template for other recurring tasks.

**Comment by CLuiz** [comment]
Anything new/interesting/confusing here so far?

**Comment by arsenyturin** [comment]
Something new definitely, things like "Fowlkes–Mallows index", that I've never heard before and some other things that are usually less covered in courses.
Also reading deeper about L1, L2 norms. I just know that they'll penalize the model so it doesn't overfit, but I've never used say L1 for features selection 🤔
