### ISSUE TITLE
Daily SQL LeetCode Practice

### ISSUE THREAD

**Issue by arsenyturin** [arsenyturin/mentorship-repo#8]
### Acceptance Criteria
- [x] Monday
- [x] Tuesday
- [ ] Wednesday
- [x] Thursday
- [x] Friday
- [ ] Saturday
- [ ] Sunday

**Comment by CLuiz** [comment]
How were these today? Get through a few? Get stuck?

**Comment by arsenyturin** [comment]
@CLuiz Went through several easy ones and one hard. Didn't get stuck, but need to work on queries to make them more compact. Since I discovered CTE's now I used them everywhere because they're easy, but makes code *possibly* unnecessary bloated.

**Comment by CLuiz** [comment]
Nice. Using CTEs tells me you already know SQL fairly well. Nice job.
