### ISSUE TITLE
Find 5 Jobs Descriptions

### ISSUE THREAD

**Issue by arsenyturin** [arsenyturin/mentorship-repo#9]
### will add title, company and short description

**Comment by CLuiz** [comment]
I'm ok with links and a brief description of why you are interested. Beyond that, added whatever is useful for you.

**Comment by arsenyturin** [comment]
- [Data Scientist](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2641100649&f_E=2%2C3&f_TPR=a1627568617-&keywords=data%20scientist&savedSearchId=1671877043&searchAlertRefId=c24642a7-76ae-4864-8e8c-5f5ccdc217f9&start=25) @ Warner Music Group
> Interested because it's a media company, opportunity to work on forecasting audience consumption
> **Doctoral Degree**, R, Python, SQL, Bayes Modeling, NLP!, Neural Networks!, Gaussian Process
- [Data Scientist - Demand Forecasting](https://www.google.com/search?q=data+scientist+in+New+York&rlz=1C5CHFA_enUS863US863&oq=data+scientist+job&aqs=chrome..69i57j69i60l3.3063j0j7&sourceid=chrome&ie=UTF-8&ibp=htl;jobs&sa=X&ved=2ahUKEwjV2NHI2pfyAhUPMVkFHbolD90Qkd0GMAJ6BAgyEAE#fpstate=tldetail&htivrt=jobs&htidocid=XleWIWc90dHBsXzHAAAAAA%3D%3D) @ Amazon
> Working at amazon with the best talents and technologies, demand forecasting
> Python, R, Scala, SQL, Hadoop, stats, analytics
- [Data Science Analyst](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2673403422&f_E=1%2C2%2C3&f_TPR=a1627568617-&keywords=data%20analyst&savedSearchId=1671878993&searchAlertRefId=037de221-e067-4d8e-b0ac-b1341fec7d95) @ CVS Health
> Entry Level, less pressure as a first job (assumptions)
> Python, R, Hadoop
- [Machine Learning Engineer](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2669427979&f_E=1%2C2%2C3&f_TPR=a1627568617-&keywords=machine%20learning%20engineer&savedSearchId=1671878503&searchAlertRefId=2acd6d5a-f2b4-4757-bf07-d30aff5394bf) @ Capital One
> Seems like a solid role based on the list of concrete requirements.
> Python, scikit-learn, PyTorch, Dask, Spark, or TensorFlow, AWS
- [Data Analyst](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2492690990&f_E=1%2C2%2C3&f_TPR=a1627568617-&keywords=data%20analyst&savedSearchId=1671878993&searchAlertRefId=037de221-e067-4d8e-b0ac-b1341fec7d95) @ Policygenius 
> Seems like a good fit. Everything I like/worked with is listed as a day-to-day work
> Analytics, Python, SQL, stats
- [Data Analyst](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2654016629&f_E=1%2C2%2C3&f_TPR=a1627568617-&keywords=data%20analyst&savedSearchId=1671878993&searchAlertRefId=037de221-e067-4d8e-b0ac-b1341fec7d95) @ The Farmer's Dog
> Seems interesting to work with pet food data, feels like uncharted territory
> SQL, R
- [Data Analyst - Emerging Markets](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2673305476&f_E=1%2C2%2C3&f_TPR=a1627568617-&keywords=data%20analyst&savedSearchId=1671878993&searchAlertRefId=037de221-e067-4d8e-b0ac-b1341fec7d95) @ Zip Co
- [Data Analyst, Digital Marketing](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2665358598&f_E=1%2C2%2C3&f_TPR=a1627568617-&keywords=data%20analyst&savedSearchId=1671878993&searchAlertRefId=037de221-e067-4d8e-b0ac-b1341fec7d95&start=25) @ Thirstie
> In general good role in the marketing field, maybe not super exciting but decent
> Python, SQL
- [Data Scientist - REMOTE](https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=2673083503&f_E=2%2C3&f_TPR=a1627568617-&keywords=data%20scientist&savedSearchId=1671877043&searchAlertRefId=c24642a7-76ae-4864-8e8c-5f5ccdc217f9&start=25) @ Eight Sleep
> Interesting company, doing analysis on sleep
> Python, SQL
